spring:
  datasource:
    url: jdbc:mysql://mysql.c88p6p0ici6s.us-east-1.rds.amazonaws.com:3306/olc2
    username: admin
    password: Lakshmi12
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

management:
  endpoints:
    web:
      exposure:
        include: "*"
